import { Badge, ItemTypes } from "../ts/globalTs";

const badges: Badge[] = [
  {
    id: 1,
    src: "src/static/images/badges_img/01_city_stroller.jpeg",
    isCollected: false,
    name: "City Stroller",
    text: "Take your first stroll through the bustling city streets",
    experience: 5,
    typeCollection: false,
    totalToCollect: 0,
    hasCollected: 0,
    type: ItemTypes.ACTIONS,
  },
  {
    id: 2,
    src: "src/static/images/badges_img/02_sky_high_challenger.jpg",
    isCollected: false,
    name: "Sky High Challenger",
    text: "Embark on your first tower stacking adventure",
    experience: 5,
    typeCollection: false,
    totalToCollect: 0,
    hasCollected: 0,
    type: ItemTypes.ACTIONS,
  },
  {
    id: 3,
    src: "src/static/images/badges_img/03_treasure_seeker.jpeg",
    isCollected: false,
    name: "Treasure Seeker",
    text: "Discover your first hidden treasure item",
    experience: 5,
    typeCollection: true,
    totalToCollect: 1,
    hasCollected: 0,
    type: ItemTypes.STAR,
  },
  {
    id: 4,
    src: "src/static/images/badges_img/04_master_collector.jpg",
    isCollected: false,
    name: "Master Collector",
    text: "Collect all the precious treasures",
    experience: 5,
    typeCollection: true,
    totalToCollect: 5,
    hasCollected: 0,
    type: ItemTypes.STAR,
  },
  {
    id: 5,
    src: "src/static/images/badges_img/05_coin_master.jpg",
    isCollected: false,
    name: "Coin Master",
    text: "Obtain your first mystical Coin",
    experience: 5,
    typeCollection: true,
    totalToCollect: 1,
    hasCollected: 0,
    type: ItemTypes.COIN,
  },
  {
    id: 6,
    src: "src/static/images/badges_img/06_car_owner.jpg",
    isCollected: false,
    name: "Car owner",
    text: "Collect all the keys to unlock the coins",
    experience: 5,
    typeCollection: true,
    totalToCollect: 3,
    hasCollected: 0,
    type: ItemTypes.COIN,
  },
  {
    id: 7,
    src: "src/static/images/badges_img/07_tower_novice.jpg",
    isCollected: false,
    name: "Tower Novice",
    text: "Reach the 5th level in the challenging tower stacking game",
    experience: 5,
    typeCollection: true,
    totalToCollect: 5,
    hasCollected: 0,
    type: ItemTypes.TOWER_GAME,
  },
  {
    id: 8,
    src: "src/static/images/badges_img/08_tower_pro.jpg",
    isCollected: false,
    name: "Tower Pro",
    text: "Show your skills and conquer the 10th level in the tower stacking game",
    experience: 10,
    typeCollection: true,
    totalToCollect: 10,
    hasCollected: 0,
    type: ItemTypes.TOWER_GAME,
  },
  {
    id: 9,
    src: "src/static/images/badges_img/09_tower_champion.jpg",
    isCollected: false,
    name: "Tower Champion",
    text: "Climb to the heights and reach the 15th level in the tower stacking game",
    experience: 15,
    typeCollection: true,
    totalToCollect: 15,
    hasCollected: 0,
    type: ItemTypes.TOWER_GAME,
  },
  {
    id: 10,
    src: "src/static/images/badges_img/10_tower_master.jpg",
    isCollected: false,
    name: "Tower Master",
    text: "Prove your tower stacking prowess by conquering the 20th level",
    experience: 20,
    typeCollection: true,
    totalToCollect: 20,
    hasCollected: 0,
    type: ItemTypes.TOWER_GAME,
  },
  {
    id: 11,
    src: "src/static/images/badges_img/11_driver.jpg",
    isCollected: false,
    name: "The driver",
    text: "Take your first drive around the city",
    experience: 10,
    typeCollection: false,
    totalToCollect: 0,
    hasCollected: 0,
    type: ItemTypes.ACTIONS,
  },
  {
    id: 12,
    src: "src/static/images/badges_img/12_Navigational_expert.jpg",
    isCollected: false,
    name: "Navigational Expert",
    text: "Mastered the art of maze exploration",
    experience: 10,
    typeCollection: true,
    totalToCollect: 1,
    hasCollected: 0,
    type: ItemTypes.DIAMOND,
  },
  {
    id: 13,
    src: "src/static/images/badges_img/13_labyrinth_conqueror.jpg",
    isCollected: false,
    name: "Labyrinth Conqueror",
    text: "Explored every nook and cranny of a mysterious maze",
    experience: 15,
    typeCollection: true,
    totalToCollect: 3,
    hasCollected: 0,
    type: ItemTypes.DIAMOND,
  },
];

export default badges;
